### ISSUE TITLE
HERE API relates to Major Trunk Roads

### ISSUE THREAD

**Issue by jeggburt** [BerkshireCar/SpeederBot#2]
On investigating the output from the HERE API, by placing various bounding boxes in residential estates, it is "limited" to those major trunk roads (A or M).

Whilst major cities may have more coverage than the suburbs, it may be worthwhile acknowledging this for people who may see more visible coverage of this.

This is from the to-be-deprecated transparent traffic map, highlighting the roads around the Tyne Tunnel.

![image](https://user-images.githubusercontent.com/25938934/130068455-fedc724d-6584-4cce-8495-ac3b3a45ab15.png)

Whilst it's a different API being hit, the output appears to provide a correlation with that produced from any bounding box return.

**Comment by BerkshireCar** [comment]
Agreed it seems to be the subject of the most support requests for help, maybe we should update the README STEP1 to highlight this and ask people to confirm if any data is returned before proceeding to STEP2 

I have managed to retrieve some data from B Roads in the area, but I know of at least 3 instances where users have not received any data relating to the road in the BBox.

**Comment by jeggburt** [comment]
I've created a pull request to update the Readme 

#3

**Comment by BerkshireCar** [comment]
Thanks @jeggburt I'll close this off for now and if people continue to comment we can re-open it.

**Comment by kamiterru** [comment]
Afternoon!

Is the above issue the reasonI am seeing data for main roads that is outside my bounding box. For example, I am getting returns for DE (streetname) of  B272 which is way outside my bounding box. [  51.4387,-0.1272;51.4227,-0.1134 ]

**Comment by BerkshireCar** [comment]
> Afternoon!
> 
> Is the above issue the reasonI am seeing data for main roads that is outside my bounding box. For example, I am getting returns for DE (streetname) of B272 which is way outside my bounding box. [ 51.4387,-0.1272;51.4227,-0.1134 ]

Quite probably hence the update to the Readme doc, HERE api does not have every road so you need to verify the DE attributes in your bounding box.

**Comment by BerkshireCar** [comment]
Recommend you check out https://twitter.com/RgntsPkSpeeders and https://github.com/chronakis/speed-monitor-bot/ it has much more detail as to the data provided by the HERE API.

**Comment by JHolah** [comment]
This is an interesting thread, and something I've not considered. I have been on other things (you know, like paid work :) ). Now that I've had time to delve into it, I fear that the data for my bot is coming from well outside the area. This is my bounding box, but DE values show A23 and A25 in the surrounding area (https://jsoneditoronline.org/#left=cloud.09233cb3133d45f89b3ac51989dc34ca). However, the data is consistent with those observed within the target area. Were it to include those roads, we would consistently be seeing data of 40-50mph. Is there a way to be more sure about the relevance of the data?

![es](https://user-images.githubusercontent.com/2090181/133595049-292c03ab-73b7-4bea-a5e0-a3d580de6391.png)

**Comment by JHolah** [comment]
Ok, so looking at the data visualisation at https://speedbot.bikesnbytes.net/, it looks like the data is way out and I'm in a similar situation to this: https://twitter.com/RgntsPkSpeeders/status/1427957749963542533. But the data I'm getting is not consistent with those A-roads so I remain confused.

Back to the drawing board...
